onlyBuiltDependencies:
  - '@wireio/protoc-gen-solana'
  - '@wireio/protoc-gen-solidity'
  - esbuild
  - protobufjs

overrides:
  '@wireio/protoc-gen-solana': link:../../../Library/pnpm/global/5/node_modules/@wireio/protoc-gen-solana
  '@wireio/protoc-gen-solidity': link:../../../Library/pnpm/global/5/node_modules/@wireio/protoc-gen-solidity
  protoc-gen-solidity: link:../../../Library/pnpm/global/5/node_modules/@wireio/protoc-gen-solidity
